# Generated by Django 3.0.4 on 2020-08-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('address1', models.TextField(max_length=700)),
                ('address2', models.TextField(max_length=700)),
                ('city', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=30)),
                ('pin_code', models.CharField(max_length=6)),
                ('lattitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('longtitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('a1', models.DecimalField(decimal_places=2, default=10, max_digits=50, verbose_name='distance limit area 1')),
                ('a2', models.DecimalField(decimal_places=2, default=3, max_digits=50, verbose_name='distance limit area 2')),
                ('a3', models.DecimalField(decimal_places=2, default=3, max_digits=50, verbose_name='distance limit area 3')),
                ('c1', models.DecimalField(decimal_places=2, default=10, max_digits=50, verbose_name='charge for area 1')),
                ('c2', models.DecimalField(decimal_places=2, default=3, max_digits=50, verbose_name='charge for area 2')),
                ('c3', models.DecimalField(decimal_places=2, default=3, max_digits=50, verbose_name='charge for area 3')),
                ('max_radius', models.DecimalField(decimal_places=2, default=15, max_digits=50, verbose_name='Maximum_Radius')),
                ('tax', models.DecimalField(decimal_places=2, default=15, max_digits=50, verbose_name='tax')),
            ],
        ),
        migrations.CreateModel(
            name='Vieworder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.IntegerField(default=1)),
                ('date_request_was_made', models.DateField(auto_now=True)),
                ('date_request_from', models.DateField(blank=True, null=True)),
                ('order_list', models.URLField(blank=True, null=True)),
                ('invoice_list', models.URLField(blank=True, null=True)),
                ('output', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
