# Generated by Django 3.0.4 on 2020-08-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=512)),
                ('category', models.TextField(max_length=512)),
                ('description', models.TextField(max_length=4096)),
                ('image_url', models.URLField(max_length=512)),
                ('regular_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('active', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
